-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM (SELECT A.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, C.AUTHOR_NAME, B.PRICE, A.SALES_DATE, A.SALES
        FROM BOOK_SALES A JOIN BOOK B ON A.BOOK_ID = B.BOOK_ID
                            JOIN AUTHOR C ON B.AUTHOR_ID =C.AUTHOR_ID
        WHERE A.SALES_DATE >= '2022-01-01' AND A.SALES_DATE <= '2022-01-31'
        ) D
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC
;