-- 코드를 입력하세요
SELECT ALLCARS.CAR_ID,
        ALLCARS.CAR_TYPE,
        FLOOR(ALLCARS.DAILY_FEE * 30 * (1 - ALLCARS.DISCOUNT_RATE / 100)) AS FEE
FROM (
        SELECT CAR.CAR_ID, CAR.CAR_TYPE, CAR.DAILY_FEE, PLAN.DISCOUNT_RATE
        FROM (
            SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
                FROM CAR_RENTAL_COMPANY_CAR C
                WHERE C.CAR_TYPE = 'SUV' OR C.CAR_TYPE = '세단'
        ) AS CAR
        LEFT JOIN (
            SELECT P.CAR_TYPE, MAX(P.DISCOUNT_RATE) AS DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
            WHERE P.DURATION_TYPE IN('30일 이상', '7일 이상')
            GROUP BY P.CAR_TYPE
        ) AS PLAN
        ON CAR.CAR_TYPE=PLAN.CAR_TYPE
        WHERE CAR.CAR_ID NOT IN (
                    SELECT HISTORY.CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
                    WHERE HISTORY.START_DATE <= '2022-11-01' AND HISTORY.END_DATE >='2022-11-01'
        )
      ) AS ALLCARS
WHERE FLOOR(ALLCARS.DAILY_FEE * 30 * (1 - ALLCARS.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC
;


                


