-- 코드를 입력하세요
SELECT USERS.USER_ID,
    USERS.NICKNAME,
    CONCAT(USERS.CITY,' ',USERS.STREET_ADDRESS1, ' ', USERS.STREET_ADDRESS2) AS '전체주소',
    CONCAT(SUBSTRING(USERS.TLNO, 1, 3), '-', SUBSTRING(USERS.TLNO, 4, 4), '-', SUBSTRING(USERS.TLNO, 8)) AS '전화번호'
FROM USED_GOODS_BOARD BOARD LEFT JOIN USED_GOODS_USER USERS
    ON BOARD.WRITER_ID = USERS.USER_ID
GROUP BY USERS.USER_ID
HAVING COUNT(USERS.USER_ID) >= 3
ORDER BY USERS.USER_ID DESC
;