-- 코드를 입력하세요
SELECT REST_ID,
        REST_NAME,
        FOOD_TYPE,
        FAVORITES,
        ADDRESS,
        ROUND(AVG(REVIEW_SCORE),2) AS SCORE

FROM (SELECT B.REST_ID, B.REST_NAME, B.FOOD_TYPE, A.REVIEW_SCORE, B.FAVORITES, B.ADDRESS
        FROM REST_REVIEW A JOIN REST_INFO B ON A.REST_ID=B.REST_ID
        WHERE B.ADDRESS LIKE '서울%') D
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
;