SELECT YEAR(SALES_DATE) AS YEAR,
        MONTH(SALES_DATE) AS MONTH,
        GENDER,
        COUNT(DISTINCT USER_ID) AS USERS
FROM (SELECT A.ONLINE_SALE_ID, A.USER_ID, A.PRODUCT_ID, A.SALES_DATE, B.GENDER
        FROM ONLINE_SALE A JOIN USER_INFO B ON A.USER_ID = B.USER_ID AND B.GENDER IS NOT NULL) C
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER

ORDER BY 1, 2, 3

;




# # SELECT YEAR(SALES_DATE) AS YEAR,
#           MONTH(SALES_DATE)AS MONTH, GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
# # FROM ONLINE_SALE A
# # JOIN USER_INFO B ON A.USER_ID = B.USER_ID
# # WHERE GENDER IS NOT NULL
# # GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER 
# # ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
# # ;