SELECT COUNT(I.FISH_TYPE) AS FISH_COUNT,
        N.FISH_NAME
FROM FISH_INFO I
    LEFT JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY 2
ORDER BY 1 DESC

;












# select FISH_NAME_INFO.FISH_NAME, COUNT(FISH_INFO.FISH_TYPE) 
# from FISH_INFO, FISH_NAME_INFO
# GROUP BY FISH_INFO.FISH_TYPE=FISH_NAME_INFO.FISH_TYPE;