-- 코드를 입력하세요

SELECT C.PRODUCT_ID,
        C.PRODUCT_NAME,
        SUM(C.PRICE*C.AMOUNT) AS TOTAL_SALES
FROM (SELECT A.PRODUCT_ID, B.PRICE, A.PRODUCE_DATE, B.PRODUCT_NAME, A.AMOUNT
        FROM FOOD_ORDER A JOIN FOOD_PRODUCT B
            ON A.PRODUCT_ID = B.PRODUCT_ID 
        WHERE A.PRODUCE_DATE >= '2022-05-01' AND A.PRODUCE_DATE <= '2022-05-31'
    ) C
GROUP BY C.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC

;