-- 코드를 입력하세요
SELECT 
        TRUCK_HISTORY.HISTORY_ID,
        CASE
            WHEN TRUCK_HISTORY.DURING = '7일 이하' THEN FLOOR(TRUCK_HISTORY.DAILY_FEE *  (DATEDIFF(TRUCK_HISTORY.END_DATE, TRUCK_HISTORY.START_DATE)+1))
            ELSE FLOOR(TRUCK_HISTORY.DAILY_FEE *  (DATEDIFF(TRUCK_HISTORY.END_DATE, TRUCK_HISTORY.START_DATE)+1) * (1 - PLAN.discount_rate / 100))
        END AS FEE
FROM(
    SELECT HISTORY.HISTORY_ID, HISTORY.CAR_ID, HISTORY.START_DATE, HISTORY.END_DATE, TRUCK.CAR_TYPE, TRUCK.DAILY_FEE, 
        CASE
            WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(HISTORY.END_DATE, HISTORY.START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE '7일 이하'
        END AS DURING
    FROM (
        SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    )AS HISTORY
    JOIN(
        SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR C
        WHERE C.CAR_TYPE = '트럭'
    )AS TRUCK
    ON HISTORY.CAR_ID = TRUCK.CAR_ID
)AS TRUCK_HISTORY
LEFT JOIN
CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
ON TRUCK_HISTORY.CAR_TYPE = PLAN.CAR_TYPE AND TRUCK_HISTORY.DURING = PLAN.DURATION_TYPE

ORDER BY FEE DESC, 1 DESC
;