-- 코드를 입력하세요
SELECT A.FLAVOR
# , SUM(A.TOTAL_ORDER+B.TOTAL_ORDER) AS TOTAL_ORDER
FROM (FIRST_HALF A LEFT JOIN (SELECT C.FLAVOR,
                                SUM(C.TOTAL_ORDER) AS TOTAL_ORDER
                        FROM JULY C
                        GROUP BY FLAVOR) B  ON A.FLAVOR = B.FLAVOR)
ORDER BY A.TOTAL_ORDER+B.TOTAL_ORDER DESC
LIMIT 3
;