-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A 
        JOIN DOCTOR C ON A.MDDR_ID = C.DR_ID AND A.MCDP_CD LIKE 'CS'
        JOIN PATIENT B ON A.PT_NO = B.PT_NO
WHERE A.APNT_CNCL_YN LIKE 'N' AND A.APNT_YMD LIKE '2022-04-13%'
    ORDER BY 6    

;