-- 코드를 작성해주세요
SELECT DISTINCT(D.ID), D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
    LEFT JOIN SKILLCODES S 
        ON (D.SKILL_CODE & S.CODE) = S.CODE
        
WHERE S.CATEGORY IS NOT NULL 
    AND S.CATEGORY LIKE 'Front End'
ORDER BY 1
 ;     
    