-- 코드를 작성해주세요
SELECT C.ITEM_ID,
        C.ITEM_NAME,
        C.RARITY
FROM ITEM_INFO A JOIN 
    (ITEM_TREE B JOIN ITEM_INFO C
        ON B.ITEM_ID = C.ITEM_ID)
    ON A.ITEM_ID = B.PARENT_ITEM_ID
        AND B.PARENT_ITEM_ID IS NOT NULL
        AND B.ITEM_ID IS NOT NULL
        AND A.RARITY ='RARE'
ORDER BY 1 DESC

;