SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE))) - SIZE_OF_COLONY AS YEAR_DEV,
        ID
FROM ECOLI_DATA
ORDER BY 1, 2
;

# SELECT YEAR(DIFFERENTIATIONDATE) AS YEAR,
#         (MAX(SIZEOFCOLONY) OVER (PARTITION BY YEAR(DIFFERENTIATIONDATE)))-SIZEOFCOLONY AS YEARDEV,
#         ID
# FROM ECOLIDATA
# ORDER BY YEAR, YEAR_DEV
# ;