SELECT B.ID,
        A.FISH_NAME,
        B.LENGTH
FROM FISH_NAME_INFO A 
    JOIN FISH_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE (A.FISH_TYPE, B.LENGTH)
        IN (SELECT FISH_TYPE, MAX(LENGTH)
            FROM FISH_INFO
            GROUP BY FISH_TYPE
        )
ORDER BY ID
;