SELECT SUM(G.SCORE) AS SCORE,
        G.EMP_NO,
        E.EMP_NAME,
        E.POSITION,
        E.EMAIL
FROM HR_GRADE G
    LEFT JOIN HR_EMPLOYEES E
    ON E.EMP_NO = G.EMP_NO
WHERE G.YEAR =2022
GROUP BY G.EMP_NO
ORDER BY 1 DESC
LIMIT 1
;