SELECT
    DEP.DEPT_ID,
    DEP.DEPT_NAME_EN,
    ROUND(AVG(EMP.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES EMP LEFT JOIN HR_DEPARTMENT DEP
    ON EMP.DEPT_ID=DEP.DEPT_ID
GROUP BY EMP.DEPT_ID
ORDER BY 3 DESC
;