SELECT A.BOARD_ID,
        A.WRITER_ID,
        A.TITLE,
        A.PRICE,
        CASE WHEN A.STATUS LIKE 'SALE' THEN '판매중'
            WHEN A.STATUS LIKE 'RESERVED' THEN '예약중'
            ELSE '거래완료'
        END AS STATUS
FROM USED_GOODS_BOARD A
WHERE A.CREATED_DATE LIKE '2022-10-05'
ORDER BY 1 DESC
;