# -- 코드를 입력하세요
# SELECT *
# FROM (SELECT *
#         FROM USED_GOODS_BOARD 
#         ORDER BY VIEWS DESC
#         LIMIT 1) AS BEST_BOARD
#         LEFT JOIN USED_GOODS_FILE FILES ON BEST_BOARD.BOARD_ID=FILES.BOARD_ID
# ORDER BY  FILES.FILE_ID, FILES.FILE_NAME, FILES.FILE_EXT


SELECT CONCAT("/home/grep/src/", FILES.BOARD_ID, "/",FILES.FILE_ID,FILES.FILE_NAME,FILES.FILE_EXT) AS FILE_PATH
FROM (SELECT *
        FROM USED_GOODS_BOARD 
        ORDER BY VIEWS DESC
        LIMIT 1) AS BEST_BOARD
        LEFT JOIN USED_GOODS_FILE FILES ON BEST_BOARD.BOARD_ID=FILES.BOARD_ID
ORDER BY  FILES.FILE_ID DESC

    
;